name: 04azure_status
on:
  workflow_run:
    workflows: ["03azure_cleanup-s", "03azure_cleanup-f"]
    branches: [main]
    types: 
      - completed

jobs:

  success:
    name: notify teams with succuess in azure environmental status
    runs-on: ubuntu-18.04
    # 呼び元のworkflowの結果が success であればmain jobを実行
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          dry_run: False
      - name: sucuess! 
        run: |
          echo '::success::Previous workflow was sucuess!'

  if_failure:
    name: notify teams with failure in azure environmental status
    runs-on: ubuntu-18.04
    # 呼び元のworkflowの結果が failure であればmain jobを実行
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          needs: ${{ toJson(needs) }}
          job: ${{ toJson(job) }}
          steps: ${{ toJson(steps) }}
          dry_run: False
      - name: make an error 
        run: |
          echo '::error::Previous workflow was failed'
